language: java
install: true
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.m2"
jobs:
  include:
  - stage: test
    name: Unit tests - OpenJDK 8
    script: mvn -B test
    jdk: openjdk8
  - name: Compile - OpenJDK 11
    if: type != pull_request
    script: mvn -B compile
    jdk: openjdk11
  - stage: deploy
    name: Deploy to Sonatype's snapshots repository
    jdk: openjdk8
    if: type != pull_request
    script: bash .travis.deploy.artifacts.sh
env:
  global:
  - secure: Pm+xPRWa4dRgOZfW4kFYrFQ8WZ7EgE87zQyhYoD+T1ktTp1TZGmBeOMG+20Aor59UO3ujitXj5xqMvGMtsGYsaKFIALAtKs/r6TVbZyrpdKcQceJIjRmGEw1Wf6Dv5/tkPEGW3v4asBLNt/vDGHf5JtAw6UzbfHHwIBRGHLSeHCD+zHWE4SxJ+suv2YxW+zidL6N7GMXGu6vYd7W2CDUfDA8vhVm+b8Q1RL+H4QFhqlDksSxZeoShl+/DHohxuK6cLJe4R1Pu0CD9KSds0vx2/x8quhtWNu9KCCY5WNyIS+x6UhrOVE7Z7xkq2KAWaVszWOHIInRC91n9RQp16ZJWx5YI1q5YrqEhoImtTDR3dITgDyulQPXMG+5mP8VbA81eXoOwak0+2Q5lv3Gn6S7pr8yNdTuo7AzYoFUw0mC1jB19whfN0UeY06su8c6cEH9+2O5jrTEb5fuTLzuzoRYwTQdrjqIwRGQr+0NIencM6NOAtu6y7J06YwKlAC1QdF6mLV855m+zQn7DJnZ4UyEt/qap4M6S68nFaWoX0nbd0qzQ9f9+ml9cOs51mh62HLsds2gO1EONVZYGbh6zYRGx0iIMA/8et0CegZ5tR0PXZ3k3/XxmT9OWvVnweigBpaSgRxHSsc4UCiUYbZ7IJGGmkDtMwzTSHtvaNXpmK+woGg=
  - secure: FU4iizVyMW2mKChIHeH434mjiPNocucclRt01P7Q5vIuhqnVdNwY0EMiJ7ZL0nRZa3lngVGLqNDTpOscVtW3yrKysQTy7wSggo82aaWl6DE2HI8mdatWKmvg7TwskczHYtA7f7nvNd+LedqcP7LW5fZzdsK6fW61GYjed9WU0Cg+mqRlFJYi6wxIAvLbayMquRJD3zivG4rhHdXV15a71f24T4rj6m6PHTGzfNpO4xiW6CGgtlLg6lgvvjWpQjV2/DPfkt+WSTQ3Gx99LCGCiCYMxETKYKKEjmZ/AHcQSBJ+ZAtsAdL4yUoLhmlqPJ8G38AafE/k6nn1Xnn4iE9XPueHXWZFXU0oLWUkitSNH1fgsrHb5SYQD1UI/3a3afesogYkDm/gpIph3xoIziVeh2hGknDmsjoC+CzVoDOSRro/Ri+C34M+i4jtxyxghj+Y9qJf5jWs2niF6ZmFpwJESrGhZN0FBYmeoleYUQRVoTEpIxzdAfMOOlwN0KbCAAYnamrpXupDG7IIXkctd3hPwHw/t2hsTfdBDydyufbA5dt4pRtO+UNY16Bq99+F7dBEcJG1NT5RjqmOdAApLyIdSdnYJn+REcAZK8TpodQ5ACZOjiyeQsv49liQU04CKAJTP62aBEgPjahmI+s+TSGuiAC4JqbxLshOjyTrxUOfTM8=
