language: java
install: true
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.m2"
jobs:
  include:
  - stage: test
    name: Unit tests - OpenJDK 8
    script: mvn -B test
    jdk: openjdk8
  - name: Compile - OpenJDK 11
    if: type != pull_request
    script: mvn -B compile
    jdk: openjdk11
  - stage: deploy
    name: Deploy to Sonatype's snapshots repository
    jdk: openjdk8
    if: type != pull_request
    script: bash .travis.deploy.artifacts.sh
env:
  global:
  - secure: dVDMFDVGgEYzfs3g3oXHvieBceMrj66edJMt94FILAlTh9+nwaKiKeKvh9OYh6tXCmf4EwQqwAkrY0GMJCYnVZ1oHF1IVlddl7O0pvNhAx0T1OhqTlluMCl3yhonqNEug7A3vDl5WT/+2R3dCRf79UJYcCe9cXPpz73wyO+UdCBKMU7n/HnwIJrMvMPkR8acNbXWH9OE8Ox+Y9Um9KRWtwwEfGR+Oheh3Dc5RVu0w2wyyReerG/RJ/dmsiSuMpvoi63t8Ht10s4smPqOIwN6fhEKJKdhshVjkKQ79sWY4Go7v4XnqqBuXpDxg4KSf6KuCJEPhEmB47eMUFcf9g1Y1LYencimOxgmiNx2U6H5XIX7kkX1LPV6oPux+nyf/09m5g6O8q0IozJovRq1biL6PdHvYkEVe52Ngo1su8FnsoO/E3xIbNAU0h7dXqgKkLMgfQ9FvIvLrstc0biJAVzvxHIyNGvLyyqdc/jfBFer6bereA/9W5IodAfgHr2QN8+o2vnrZkcv/MyjeFTbvui17dMD0nHnDpvuK8DtGtK2zVfL8Z9gL9tAD8LiRSn8UraZFtBdH6h0tGqpYsPxglJttlkdt8MnwZguAaKnNZZ8c+8uLLUyGAVpwiNbXBmudACFwfCsosxKBDOMsai+y5UCdI/yrbIQW657ov82sf5sCXw=
  - secure: N2jn4W8fHm+2iSDHDI1vcPMUCG1u1iMMLzB5ZtdqHNm+dMSA2+GDHwt/v/Bm/yJXGq/jBbENmdBM6UPE60ytkwfP0t58SxFYlyUIOb+Dg7+YBktSirEUh9SEid9BAPgPz1oTNb9oritzan1aw7pxoeMLK80MzA8kz00nwoWSTisW7uvmwzZnYiV6JZ8gqokOW/KWSooBfByfLoH8T3pUOEDAOjnGiN+LEUGI9hcNJMZiBe9vzwtpZ8RTkwATixzYBt4WdsxA9FqKt0upb1XFw6gDHo3F+nD3xjYhsP4werwcWpnHOMPqvZqiwr7teXCweMDbZHI9/aqlDGsSbdFPTDPtiAKyAQvGkbHdhfl6xuzxDrEm0NQB4RGFaIXq0WJNE7hRN8AE5vNvHrkUFC0aB+qWZS3q66DNyMI5PteMVVXX7h9K2UOjFsJykuJbOqQKV5bebOn8NRwOyeiJLt0jmef8XDC9vayN7GIbZiFr3IAV0QJCecVj3hFYS9HEJbD3sMuDuWUPNJ9FSQmNtc/bbWEt6PgUGIpASwkC77mkfAYruy/ttmV9zHW4XUOcPocKEdFfO9Rg2mZSivheAjkKbRi9rTLjLzhElpN8QYktQzRzKLj7lURCt0Yzk3DqT51y7b6c1cqV74oUvV9Sv+vAzcOEEz0HXoWZ0orSKr9STCA=
